worker_processes 1;
pid data/runtime/nginx.pid;
error_log data/runtime/nginx.error.log warn;

events {
    worker_connections 1024;
}

http {
    include /etc/nginx/mime.types;
    default_type application/octet-stream;
    access_log data/runtime/nginx.access.log;
    sendfile on;

    include gamma-proxy.conf;
}
